services:
  familytimeline-server:
    build:
      context: ./backend-server
    environment:
      - NODE_ENV=development
    volumes:
      - ./userdata/database.sqlite3:/app/src/utils/database.sqlite3
      - ./userdata/data/:/app/src/data/
      
  familytimeline-client:
    build:
      context: ./vuejs-client
    volumes:
      - ./userdata/config.js:/usr/share/nginx/html/config.js
      
  familytimeline-nginx:
    image: nginx:1.24.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./userdata/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - familytimeline-server
      - familytimeline-client
